# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42536768f866ff9cae2080fe5475077ea9c778fd0b398cd9c24874d0f8672c60b88c664f23ea16728b7c9864ab54ca5d6673a5db45c562c9b1c89ae2c1363261

test:
  secret_key_base: 2d3fa4cd6244ffe06c65d14431f6eff0dfa11ef0c3cd30e79943ca470e87044c9ac5448fcd7fa7deedb9d76b0cd2590bc248c6eb4c4af3effd735dea9bd9608a

# Do not keep server secrets in the repository,
# instead read values from the environment.
acceptance:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
